sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: 10.0.0.200
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: wx2d8aa413a88e488d
    secret: 1b636ec62a174d791b5c861944467075